### ISSUE TITLE
Web version has different login interface?

### ISSUE THREAD

**Issue by CellCS** [syncwithadifens/flutterui#1]
when build on web by using '''flutter run -d chrome'''

get this 
<img width="503" alt="image" src="https://github.com/syncwithadifens/flutterui/assets/16886624/d545c0dd-a20c-4ad7-8906-c211e9d27b23">

**Comment by syncwithadifens** [comment]
Oh sorry for late reply, u need to change route in main.dart for specific page what u need to show first.
